import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { DecisionIndexItem } from '../../types/decision.js';
import { slugify } from '../store.js';
import { atomicWriteFile } from './markers.js';

export interface CursorExportResult {
  created: string[];
  updated: string[];
  deleted: string[];
  unchanged: string[];
}

export interface CursorCheckResult {
  inSync: boolean;
  missingFiles: string[];
  outOfSyncFiles: string[];
  staleFiles: string[];
}

export function getCursorRuleFilename(
  dec: DecisionIndexItem,
  allActive: DecisionIndexItem[]
): string {
  const baseSlug = slugify(dec.summary);
  const duplicates = allActive.filter((d) => slugify(d.summary) === baseSlug);
  if (duplicates.length > 1) {
    return `${baseSlug}-${dec.id}.mdc`;
  }
  return `${baseSlug}.mdc`;
}

export function generateCursorRuleContent(dec: DecisionIndexItem): string {
  const globs =
    dec.scope.length === 1
      ? dec.scope[0]
      : dec.scope.length > 1
      ? dec.scope
      : '';

  const frontmatter = {
    description: dec.summary,
    globs,
    alwaysApply: false
  };

  const bodyParts = [
    `<!-- Generated by decision-tracker: ${dec.id} -->`,
    '',
    `# ${dec.summary}`,
    '',
    `- **ID**: ${dec.id}`,
    `- **Status**: ${dec.status}`,
    `- **Author**: ${dec.author}`,
    `- **Confidence**: ${dec.confidence}`
  ];

  if (dec.tags && dec.tags.length > 0) {
    bodyParts.push(`- **Tags**: ${dec.tags.join(', ')}`);
  }

  bodyParts.push('', '## Rationale', dec.rationale);

  if (dec.context) {
    bodyParts.push('', '## Context', dec.context);
  }
  if (dec.consequences) {
    bodyParts.push('', '## Consequences', dec.consequences);
  }

  return matter.stringify(bodyParts.join('\n') + '\n', frontmatter);
}

export function exportCursorRules(
  baseDir: string,
  decisions: DecisionIndexItem[]
): CursorExportResult {
  const cursorRulesDir = path.join(baseDir, '.cursor', 'rules');
  if (!fs.existsSync(cursorRulesDir)) {
    fs.mkdirSync(cursorRulesDir, { recursive: true });
  }

  const active = decisions
    .filter((d) => d.status === 'active')
    .sort((a, b) => a.id.localeCompare(b.id));

  const activeIds = new Set(active.map((d) => d.id));
  const expectedFileNames = new Set<string>();

  const result: CursorExportResult = {
    created: [],
    updated: [],
    deleted: [],
    unchanged: []
  };

  // 1. Write or update active rules
  for (const dec of active) {
    const filename = getCursorRuleFilename(dec, active);
    expectedFileNames.add(filename);
    const targetPath = path.join(cursorRulesDir, filename);
    const expectedContent = generateCursorRuleContent(dec);

    if (fs.existsSync(targetPath)) {
      const existing = fs.readFileSync(targetPath, 'utf8');
      if (existing === expectedContent) {
        result.unchanged.push(path.relative(baseDir, targetPath).replace(/\\/g, '/'));
      } else {
        atomicWriteFile(targetPath, expectedContent);
        result.updated.push(path.relative(baseDir, targetPath).replace(/\\/g, '/'));
      }
    } else {
      atomicWriteFile(targetPath, expectedContent);
      result.created.push(path.relative(baseDir, targetPath).replace(/\\/g, '/'));
    }
  }

  // 2. Clean up stale rules that were generated by decision-tracker
  if (fs.existsSync(cursorRulesDir)) {
    const existingFiles = fs.readdirSync(cursorRulesDir);
    for (const file of existingFiles) {
      if (!file.endsWith('.mdc')) continue;
      const fullPath = path.join(cursorRulesDir, file);
      try {
        const content = fs.readFileSync(fullPath, 'utf8');
        const markerMatch = content.match(/<!-- Generated by decision-tracker:\s*([a-zA-Z0-9_-]+)\s*-->/);
        if (markerMatch) {
          const decId = markerMatch[1];
          // If decision is no longer active OR if filename is no longer expected
          if (!activeIds.has(decId) || !expectedFileNames.has(file)) {
            fs.unlinkSync(fullPath);
            result.deleted.push(path.relative(baseDir, fullPath).replace(/\\/g, '/'));
          }
        }
      } catch {}
    }
  }

  return result;
}

export function checkCursorRules(
  baseDir: string,
  decisions: DecisionIndexItem[]
): CursorCheckResult {
  const cursorRulesDir = path.join(baseDir, '.cursor', 'rules');
  const active = decisions
    .filter((d) => d.status === 'active')
    .sort((a, b) => a.id.localeCompare(b.id));

  const activeIds = new Set(active.map((d) => d.id));
  const expectedFileNames = new Set<string>();

  const result: CursorCheckResult = {
    inSync: true,
    missingFiles: [],
    outOfSyncFiles: [],
    staleFiles: []
  };

  for (const dec of active) {
    const filename = getCursorRuleFilename(dec, active);
    expectedFileNames.add(filename);
    const targetPath = path.join(cursorRulesDir, filename);
    const rel = path.relative(baseDir, targetPath).replace(/\\/g, '/');
    const expectedContent = generateCursorRuleContent(dec);

    if (!fs.existsSync(targetPath)) {
      result.missingFiles.push(rel);
      result.inSync = false;
    } else {
      const existing = fs.readFileSync(targetPath, 'utf8');
      if (existing !== expectedContent) {
        result.outOfSyncFiles.push(rel);
        result.inSync = false;
      }
    }
  }

  if (fs.existsSync(cursorRulesDir)) {
    const existingFiles = fs.readdirSync(cursorRulesDir);
    for (const file of existingFiles) {
      if (!file.endsWith('.mdc')) continue;
      const fullPath = path.join(cursorRulesDir, file);
      const rel = path.relative(baseDir, fullPath).replace(/\\/g, '/');
      try {
        const content = fs.readFileSync(fullPath, 'utf8');
        const markerMatch = content.match(/<!-- Generated by decision-tracker:\s*([a-zA-Z0-9_-]+)\s*-->/);
        if (markerMatch) {
          const decId = markerMatch[1];
          if (!activeIds.has(decId) || !expectedFileNames.has(file)) {
            result.staleFiles.push(rel);
            result.inSync = false;
          }
        }
      } catch {}
    }
  }

  return result;
}
