import fs from 'fs';
import path from 'path';

export const BEGIN_MARKER = '<!-- BEGIN:decision-tracker -->';
export const END_MARKER = '<!-- END:decision-tracker -->';

export function injectManagedSection(
  existingContent: string,
  newManagedContent: string,
  filePathForError: string = 'file'
): { content: string; changed: boolean } {
  // Detect CRLF vs LF
  const isCrlf = existingContent.includes('\r\n');
  const eol = isCrlf ? '\r\n' : '\n';

  // Normalize newManagedContent to the detected EOL
  const normalizedManaged = newManagedContent
    .replace(/\r\n/g, '\n')
    .replace(/\n/g, eol)
    .trim();

  const beginRegex = new RegExp(escapeRegex(BEGIN_MARKER), 'g');
  const endRegex = new RegExp(escapeRegex(END_MARKER), 'g');

  const beginMatches = [...existingContent.matchAll(beginRegex)];
  const endMatches = [...existingContent.matchAll(endRegex)];

  if (beginMatches.length > 1 || endMatches.length > 1) {
    throw new Error(
      `Multiple managed-section markers found in ${filePathForError}. Expected at most one BEGIN and one END marker.`
    );
  }

  if (beginMatches.length === 1 && endMatches.length === 0) {
    throw new Error(
      `Unbalanced managed-section markers in ${filePathForError}: found BEGIN without matching END marker.`
    );
  }

  if (beginMatches.length === 0 && endMatches.length === 1) {
    throw new Error(
      `Unbalanced managed-section markers in ${filePathForError}: found END without matching BEGIN marker.`
    );
  }

  const generatedBlock = [
    BEGIN_MARKER,
    '<!-- Generated by decision-tracker. Do not edit this block directly. -->',
    '',
    normalizedManaged,
    '',
    END_MARKER
  ].join(eol);

  let newFullContent: string;

  if (beginMatches.length === 0 && endMatches.length === 0) {
    // Append to existing content or initialize
    const trimmed = existingContent.trimEnd();
    if (trimmed.length === 0) {
      newFullContent = generatedBlock + eol;
    } else {
      newFullContent = trimmed + eol + eol + generatedBlock + eol;
    }
  } else {
    const beginIndex = beginMatches[0].index;
    const endIndex = endMatches[0].index;

    if (endIndex < beginIndex) {
      throw new Error(
        `Invalid managed-section markers in ${filePathForError}: END marker appears before BEGIN marker.`
      );
    }

    const prefix = existingContent.slice(0, beginIndex);
    const suffix = existingContent.slice(endIndex + END_MARKER.length);
    newFullContent = prefix + generatedBlock + suffix;
  }

  const changed = newFullContent !== existingContent;
  return { content: newFullContent, changed };
}

export function atomicWriteFile(targetPath: string, content: string): void {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const tempPath = path.join(
    dir,
    `.tmp-${path.basename(targetPath)}-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );

  fs.writeFileSync(tempPath, content, 'utf-8');
  try {
    fs.renameSync(tempPath, targetPath);
  } catch (err: any) {
    // Windows fallback: if destination exists and cannot be renamed atomically, remove and rename
    if (fs.existsSync(targetPath)) {
      try {
        fs.unlinkSync(targetPath);
      } catch {}
    }
    fs.renameSync(tempPath, targetPath);
  }
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
