import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import matter from 'gray-matter';
import {
  injectManagedSection,
  atomicWriteFile,
  BEGIN_MARKER,
  END_MARKER
} from '../src/core/exporters/markers.js';
import { formatDecisionsMarkdown } from '../src/core/exporters/markdown.js';
import {
  exportCursorRules,
  checkCursorRules,
  getCursorRuleFilename
} from '../src/core/exporters/cursor.js';
import { installPreCommitHook } from '../src/core/exporters/git.js';
import {
  exportDecisions,
  checkExport
} from '../src/core/exporters/index.js';
import { recordDecision, initStorage, updateDecisionStatus } from '../src/core/store.js';
import { DecisionIndexItem } from '../src/types/decision.js';

describe('Feature 3: Multi-Agent Export', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'dt-export-test-'));
  });

  afterEach(() => {
    if (fs.existsSync(tmpDir)) {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  describe('Managed Section Markers & Injection', () => {
    it('injects managed section into empty content', () => {
      const res = injectManagedSection('', 'Some managed rules');
      expect(res.changed).toBe(true);
      expect(res.content).toContain(BEGIN_MARKER);
      expect(res.content).toContain(END_MARKER);
      expect(res.content).toContain('Some managed rules');
    });

    it('appends managed section to existing content without markers', () => {
      const existing = '# Existing Documentation\n\nDo not overwrite this.';
      const res = injectManagedSection(existing, 'New generated content');
      expect(res.changed).toBe(true);
      expect(res.content.startsWith('# Existing Documentation')).toBe(true);
      expect(res.content).toContain(BEGIN_MARKER);
      expect(res.content).toContain('New generated content');
      expect(res.content).toContain(END_MARKER);
    });

    it('replaces only the managed section when markers exist', () => {
      const existing = [
        '# Header',
        'intro text',
        BEGIN_MARKER,
        '<!-- Generated by decision-tracker. Do not edit this block directly. -->',
        '',
        'Old decisions',
        '',
        END_MARKER,
        'Footer text'
      ].join('\n');

      const res = injectManagedSection(existing, 'Updated decisions');
      expect(res.changed).toBe(true);
      expect(res.content).toContain('# Header');
      expect(res.content).toContain('Footer text');
      expect(res.content).toContain('Updated decisions');
      expect(res.content).not.toContain('Old decisions');
    });

    it('preserves CRLF line endings when present in original file', () => {
      const existingCrlf = '# Header\r\nIntro\r\n' + BEGIN_MARKER + '\r\nold\r\n' + END_MARKER + '\r\nFooter\r\n';
      const res = injectManagedSection(existingCrlf, 'New content');
      expect(res.content).toContain('\r\n');
      expect(res.content).not.toMatch(/[^\r]\n/);
    });

    it('preserves LF line endings when present in original file', () => {
      const existingLf = '# Header\nIntro\n' + BEGIN_MARKER + '\nold\n' + END_MARKER + '\nFooter\n';
      const res = injectManagedSection(existingLf, 'New content');
      expect(res.content).not.toContain('\r\n');
      expect(res.content).toContain('\n');
    });

    it('throws descriptive error on unbalanced markers: BEGIN without END', () => {
      const broken = '# Header\n' + BEGIN_MARKER + '\nsome content without end';
      expect(() => injectManagedSection(broken, 'new', 'AGENTS.md')).toThrow(
        /Unbalanced managed-section markers in AGENTS.md: found BEGIN without matching END marker/
      );
    });

    it('throws descriptive error on unbalanced markers: END without BEGIN', () => {
      const broken = '# Header\nsome content without begin\n' + END_MARKER;
      expect(() => injectManagedSection(broken, 'new', 'AGENTS.md')).toThrow(
        /Unbalanced managed-section markers in AGENTS.md: found END without matching BEGIN marker/
      );
    });

    it('throws error when multiple markers are present', () => {
      const broken = [
        BEGIN_MARKER,
        END_MARKER,
        BEGIN_MARKER,
        END_MARKER
      ].join('\n');
      expect(() => injectManagedSection(broken, 'new', 'AGENTS.md')).toThrow(
        /Multiple managed-section markers found/
      );
    });

    it('throws error when END marker appears before BEGIN marker', () => {
      const inverted = [
        END_MARKER,
        'some content',
        BEGIN_MARKER
      ].join('\n');
      expect(() => injectManagedSection(inverted, 'new', 'AGENTS.md')).toThrow(
        /Invalid managed-section markers in AGENTS.md: END marker appears before BEGIN marker/
      );
    });

    it('atomicWriteFile writes content safely', () => {
      const targetFile = path.join(tmpDir, 'nested', 'test.txt');
      atomicWriteFile(targetFile, 'Hello atomic');
      expect(fs.readFileSync(targetFile, 'utf8')).toBe('Hello atomic');
    });
  });

  describe('Markdown Formatter for Managed Sections', () => {
    const sampleDecisions: DecisionIndexItem[] = [
      {
        id: 'dec_20260101_000001',
        summary: 'Use PostgreSQL for database',
        rationale: 'PostgreSQL provides robust ACID transactions and JSONB support.',
        scope: ['src/db/**/*.ts', 'prisma/schema.prisma'],
        tags: ['database', 'postgres'],
        author: 'alice',
        status: 'active',
        confidence: 'explicit',
        created: '2026-01-01T10:00:00.000Z',
        filePath: '.decisions/active/use-postgresql.md'
      },
      {
        id: 'dec_20260102_000002',
        summary: 'Use Vitest for unit tests',
        rationale: 'Vitest is fast, native to ESM, and compatible with Vite config.',
        scope: ['tests/**/*.test.ts'],
        tags: ['testing'],
        author: 'bob',
        status: 'active',
        confidence: 'explicit',
        created: '2026-01-02T10:00:00.000Z',
        filePath: '.decisions/active/use-vitest.md'
      },
      {
        id: 'dec_20260103_000003',
        summary: 'Superseded decision',
        rationale: 'Old rationale',
        scope: ['**/*'],
        tags: ['old'],
        author: 'charlie',
        status: 'superseded',
        confidence: 'explicit',
        created: '2026-01-03T10:00:00.000Z',
        filePath: '.decisions/superseded/old.md'
      }
    ];

    it('formats active decisions deterministically and ignores non-active ones', () => {
      const output = formatDecisionsMarkdown(sampleDecisions);
      expect(output).toContain('## Architectural Decisions');
      expect(output).toContain('[dec_20260102_000002] Use Vitest for unit tests');
      expect(output).toContain('[dec_20260101_000001] Use PostgreSQL for database');
      expect(output).not.toContain('Superseded decision');
    });

    it('formats scope correctly with code backticks or needs-scope fallback', () => {
      const noScopeDec: DecisionIndexItem[] = [
        {
          id: 'dec_20260104_000004',
          summary: 'Global logging standard',
          rationale: 'Standardize logging format.',
          scope: [],
          tags: ['logging'],
          author: 'alice',
          status: 'active',
          confidence: 'explicit',
          created: '2026-01-04T10:00:00.000Z',
          filePath: '.decisions/active/logging.md'
        }
      ];
      const output = formatDecisionsMarkdown(noScopeDec);
      expect(output).toContain('**Scope**: All files (`needs-scope`)');
    });

    it('truncates rationale when exceeding maxRationaleLen', () => {
      const longRationaleDec: DecisionIndexItem[] = [
        {
          id: 'dec_20260105_000005',
          summary: 'Long rationale decision',
          rationale: 'A'.repeat(500),
          scope: ['src/**/*'],
          tags: [],
          author: 'alice',
          status: 'active',
          confidence: 'explicit',
          created: '2026-01-05T10:00:00.000Z',
          filePath: '.decisions/active/long.md'
        }
      ];
      const output = formatDecisionsMarkdown(longRationaleDec, { maxRationaleLen: 100 });
      expect(output).toContain('A'.repeat(100) + '...');
      expect(output).not.toContain('A'.repeat(101));
    });

    it('caps max decisions and prints overflow notice', () => {
      const output = formatDecisionsMarkdown(sampleDecisions, { maxDecisions: 1 });
      expect(output).toContain('[dec_20260102_000002]');
      expect(output).not.toContain('[dec_20260101_000001]');
      expect(output).toContain('and 1 more active decisions');
    });
  });

  describe('Cursor MDC Rules Exporter', () => {
    it('creates .cursor/rules/<slug>.mdc with correct frontmatter and body', () => {
      const decisions: DecisionIndexItem[] = [
        {
          id: 'dec_20260201_test01',
          summary: 'Use Zod for input validation',
          rationale: 'Provides runtime schema validation.',
          scope: ['src/types/**/*.ts', 'src/api/**/*.ts'],
          tags: ['zod', 'validation'],
          author: 'dave',
          status: 'active',
          confidence: 'explicit',
          created: '2026-02-01T10:00:00.000Z',
          filePath: '.decisions/active/use-zod.md'
        }
      ];

      const res = exportCursorRules(tmpDir, decisions);
      expect(res.created.length).toBe(1);

      const ruleFile = path.join(tmpDir, '.cursor', 'rules', 'use-zod-for-input-validation.mdc');
      expect(fs.existsSync(ruleFile)).toBe(true);

      const parsed = matter(fs.readFileSync(ruleFile, 'utf8'));
      expect(parsed.data.description).toBe('Use Zod for input validation');
      expect(parsed.data.globs).toEqual(['src/types/**/*.ts', 'src/api/**/*.ts']);
      expect(parsed.data.alwaysApply).toBe(false);
      expect(parsed.content).toContain('<!-- Generated by decision-tracker: dec_20260201_test01 -->');
      expect(parsed.content).toContain('## Rationale');
      expect(parsed.content).toContain('Provides runtime schema validation.');
    });

    it('handles slug collisions deterministically', () => {
      const dec1: DecisionIndexItem = {
        id: 'dec_aaa',
        summary: 'Consistent naming',
        rationale: 'r1',
        scope: ['src/**/*'],
        tags: [],
        author: 'a',
        status: 'active',
        confidence: 'explicit',
        created: '2026-02-01T10:00:00.000Z',
        filePath: 'f1'
      };
      const dec2: DecisionIndexItem = {
        id: 'dec_bbb',
        summary: 'Consistent naming',
        rationale: 'r2',
        scope: ['tests/**/*'],
        tags: [],
        author: 'b',
        status: 'active',
        confidence: 'explicit',
        created: '2026-02-02T10:00:00.000Z',
        filePath: 'f2'
      };

      const filename1 = getCursorRuleFilename(dec1, [dec1, dec2]);
      const filename2 = getCursorRuleFilename(dec2, [dec1, dec2]);
      expect(filename1).toBe('consistent-naming-dec_aaa.mdc');
      expect(filename2).toBe('consistent-naming-dec_bbb.mdc');
    });

    it('cleans up stale generated rules when decisions are removed or superseded', () => {
      const dec: DecisionIndexItem = {
        id: 'dec_to_supersede',
        summary: 'Old architecture pattern',
        rationale: 'Old pattern',
        scope: ['src/**/*'],
        tags: [],
        author: 'a',
        status: 'active',
        confidence: 'explicit',
        created: '2026-02-01T10:00:00.000Z',
        filePath: 'f'
      };

      // Export while active
      exportCursorRules(tmpDir, [dec]);
      const expectedPath = path.join(tmpDir, '.cursor', 'rules', 'old-architecture-pattern.mdc');
      expect(fs.existsSync(expectedPath)).toBe(true);

      // Now decision is superseded (not in active list)
      const res2 = exportCursorRules(tmpDir, []);
      expect(res2.deleted.length).toBe(1);
      expect(fs.existsSync(expectedPath)).toBe(false);
    });

    it('preserves user-defined .mdc files not generated by decision-tracker', () => {
      const cursorDir = path.join(tmpDir, '.cursor', 'rules');
      fs.mkdirSync(cursorDir, { recursive: true });
      const customUserRule = path.join(cursorDir, 'custom-team-rule.mdc');
      fs.writeFileSync(customUserRule, '---\ndescription: My custom rule\n---\nDo not touch!', 'utf8');

      const res = exportCursorRules(tmpDir, []);
      expect(res.deleted.length).toBe(0);
      expect(fs.existsSync(customUserRule)).toBe(true);
    });

    it('checkCursorRules detects missing, out-of-sync, and stale rules', () => {
      const dec: DecisionIndexItem = {
        id: 'dec_check_test',
        summary: 'Check test rule',
        rationale: 'Testing check',
        scope: ['src/**/*.ts'],
        tags: [],
        author: 'a',
        status: 'active',
        confidence: 'explicit',
        created: '2026-02-01T10:00:00.000Z',
        filePath: 'f'
      };

      // Before export: missing
      const check1 = checkCursorRules(tmpDir, [dec]);
      expect(check1.inSync).toBe(false);
      expect(check1.missingFiles.length).toBe(1);

      // After export: in sync
      exportCursorRules(tmpDir, [dec]);
      const check2 = checkCursorRules(tmpDir, [dec]);
      expect(check2.inSync).toBe(true);

      // Mutate rule: out of sync
      const rulePath = path.join(tmpDir, '.cursor', 'rules', 'check-test-rule.mdc');
      fs.writeFileSync(rulePath, 'corrupted content', 'utf8');
      const check3 = checkCursorRules(tmpDir, [dec]);
      expect(check3.inSync).toBe(false);
      expect(check3.outOfSyncFiles.length).toBe(1);
    });
  });

  describe('Pre-commit Hook Installer', () => {
    it('installs to .husky/pre-commit when husky directory exists', () => {
      const huskyDir = path.join(tmpDir, '.husky');
      fs.mkdirSync(huskyDir, { recursive: true });

      const res = installPreCommitHook(tmpDir);
      expect(res.hookType).toBe('husky');
      expect(res.created).toBe(true);
      const hookPath = path.join(tmpDir, '.husky', 'pre-commit');
      expect(fs.existsSync(hookPath)).toBe(true);
      expect(fs.readFileSync(hookPath, 'utf8')).toContain('npx decision-tracker export --check');

      // Second run is idempotent
      const res2 = installPreCommitHook(tmpDir);
      expect(res2.created).toBe(false);
      expect(res2.updated).toBe(false);
    });

    it('installs to .git/hooks/pre-commit as fallback', () => {
      const gitHooksDir = path.join(tmpDir, '.git', 'hooks');
      fs.mkdirSync(gitHooksDir, { recursive: true });

      const res = installPreCommitHook(tmpDir);
      expect(res.hookType).toBe('git');
      expect(res.created).toBe(true);
      const hookPath = path.join(gitHooksDir, 'pre-commit');
      expect(fs.existsSync(hookPath)).toBe(true);
      expect(fs.readFileSync(hookPath, 'utf8')).toContain('npx decision-tracker export --check');
    });

    it('appends to existing pre-commit hook without overwriting existing commands', () => {
      const gitHooksDir = path.join(tmpDir, '.git', 'hooks');
      fs.mkdirSync(gitHooksDir, { recursive: true });
      const hookPath = path.join(gitHooksDir, 'pre-commit');
      fs.writeFileSync(hookPath, '#!/bin/sh\nnpm run lint\n', 'utf8');

      const res = installPreCommitHook(tmpDir);
      expect(res.updated).toBe(true);
      const content = fs.readFileSync(hookPath, 'utf8');
      expect(content).toContain('npm run lint');
      expect(content).toContain('npx decision-tracker export --check');
    });
  });

  describe('Full exportDecisions and checkExport Integration', () => {
    beforeEach(() => {
      initStorage(tmpDir);
      recordDecision(tmpDir, {
        summary: 'Architecture Decision 1',
        rationale: 'Rationale for 1',
        scope: ['src/core/**/*.ts'],
        tags: ['core']
      });
      recordDecision(tmpDir, {
        summary: 'Architecture Decision 2',
        rationale: 'Rationale for 2',
        scope: ['src/cli/**/*.ts'],
        tags: ['cli']
      });
    });

    it('exports to all targets and verifies --check mode', () => {
      // 1. Initial check fails because files do not exist yet
      const checkBefore = checkExport({ baseDir: tmpDir });
      expect(checkBefore.inSync).toBe(false);

      // 2. Export all targets
      const exportRes = exportDecisions({ baseDir: tmpDir });
      expect(exportRes.success).toBe(true);

      // Verify files created
      expect(fs.existsSync(path.join(tmpDir, 'AGENTS.md'))).toBe(true);
      expect(fs.existsSync(path.join(tmpDir, '.github', 'copilot-instructions.md'))).toBe(true);
      expect(fs.existsSync(path.join(tmpDir, '.windsurfrules'))).toBe(true);
      expect(fs.existsSync(path.join(tmpDir, '.cursor', 'rules', 'architecture-decision-1.mdc'))).toBe(true);
      expect(fs.existsSync(path.join(tmpDir, '.cursor', 'rules', 'architecture-decision-2.mdc'))).toBe(true);

      // 3. Check export now reports inSync: true
      const checkAfter = checkExport({ baseDir: tmpDir });
      expect(checkAfter.inSync).toBe(true);
      expect(checkAfter.targets.every((t) => t.inSync)).toBe(true);

      // 4. Modifying AGENTS.md causes check to fail
      const agentsMdPath = path.join(tmpDir, 'AGENTS.md');
      const agentsContent = fs.readFileSync(agentsMdPath, 'utf8');
      fs.writeFileSync(agentsMdPath, agentsContent.replace('Architecture Decision 1', 'Tampered Decision'), 'utf8');

      const checkTampered = checkExport({ baseDir: tmpDir });
      expect(checkTampered.inSync).toBe(false);
      const agentsTarget = checkTampered.targets.find((t) => t.target === 'agents-md');
      expect(agentsTarget?.inSync).toBe(false);

      // 5. Re-exporting fixes it
      exportDecisions({ baseDir: tmpDir, target: 'agents-md' });
      const checkFixed = checkExport({ baseDir: tmpDir, target: 'agents-md' });
      expect(checkFixed.inSync).toBe(true);
    });

    it('superseding a decision updates managed sections and removes stale cursor rules on re-export', () => {
      exportDecisions({ baseDir: tmpDir });

      const index = checkExport({ baseDir: tmpDir });
      expect(index.inSync).toBe(true);

      // Add a third decision and supersede the first
      const d1Record = recordDecision(tmpDir, {
        summary: 'Architecture Decision 3 Superseding 1',
        rationale: 'New approach',
        scope: ['src/core/**/*.ts'],
        tags: ['core']
      });

      // Update decision 1 status to superseded
      const activeDecs = fs.readdirSync(path.join(tmpDir, '.decisions', 'active'));
      const dec1File = activeDecs.find((f) => f.includes('architecture-decision-1'));
      const dec1Id = matter(fs.readFileSync(path.join(tmpDir, '.decisions', 'active', dec1File!), 'utf8')).data.id;

      updateDecisionStatus(tmpDir, dec1Id, 'superseded', d1Record.id);

      // Re-export
      exportDecisions({ baseDir: tmpDir });

      // Cursor rule 1 should have been cleaned up
      const oldCursorRule = path.join(tmpDir, '.cursor', 'rules', 'architecture-decision-1.mdc');
      expect(fs.existsSync(oldCursorRule)).toBe(false);

      // Cursor rule 3 should exist
      const newCursorRule = path.join(tmpDir, '.cursor', 'rules', 'architecture-decision-3-superseding-1.mdc');
      expect(fs.existsSync(newCursorRule)).toBe(true);

      // Check is clean
      const finalCheck = checkExport({ baseDir: tmpDir });
      expect(finalCheck.inSync).toBe(true);
    });
  });
});
